### ISSUE TITLE
Please add your ideas and small projects

### ISSUE THREAD

**Issue by oshyam** [oshyam/Ideas-and-applications#1]

**Comment by ankitminglani** [comment]
Hi Oshyam,
Do you need a working project git repo or just the idea ?

**Comment by oshyam** [comment]
@ankitminglani An Idea that can shape the future + any small application, if not able to make please submit ideas related to that.

**Comment by ankitminglani** [comment]
@oshyam I think thats very open ended. Shape the future for whom ? I was working on a beginner's project like a random recipe generator, would that work ? its still a simple project idea. 

I do have other ideas but they are not implemented yet. should i create a pull request for couple of ideas ? beginner/intermediate level ?

**Comment by oshyam** [comment]
every idea can be ultimately turned into a piece of software, if you have any project you can add or you can add ideas as of now, you can add project later but it would be better if you add projects too..also star the repo if you think this small change can help & reach to others.
